# Generated by Django 4.2.11 on 2024-07-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_item_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images-<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
